document.write('<link href="../style.css" rel="stylesheet" type="text/css"> ')
document.write('<div align="center">')
document.write('<table width="750" height="17" border="0" align="center" cellpadding="0" cellspacing="0" class="unnamed2">')
document.write('  </table>')
document.write('  </table>')
document.write('  <table width="750" border="0" cellspacing="0" cellpadding="0" align="center">')
document.write('    <tr> ')
document.write('      <td width="100" background="http://theme.xoops.org.cn/theme/themes/sw_web2/images/bg_footer.gif" bgcolor=#FFFFFF> ')
document.write('        </div></td>')
document.write('      <td width="600" background="http://theme.xoops.org.cn/theme/themes/sw_web2/images/bg_footer.gif" bgcolor=#FFFFFF> ')
document.write('        <div align="center"> ')
document.write('          <p><span class="unnamed1"><font color="#000000"><br>')
document.write('            <font color="#000000">XOOPS 作为世界上流行的web CMS系统，凝聚世界各地钟爱开源精神的开发者和支持者，北至爱尔兰南至澳大利亚、阿根廷,东自中国日本西到美国加拿大,无不可见为了开源社区而奉献的人们.</font></font></span></p>')
document.write('          </div></td>')
document.write('      <td background="001" bgcolor=#FFFFFF> ')
document.write('        <div align="center"></div></td>')
document.write(' <td background="http://theme.xoops.org.cn/theme/themes/sw_web2/images/bg_footer.gif" bgcolor=#FFFFFF>  ')
document.write('         <div align="center"><a href="http://creativecommons.org/licenses/by-nc-sa/2.0/"><img src="http://theme.xoops.org.cn/theme/themes/sw_web2/images/cc.gif" border="0"></a></div></td> ')
document.write('    </tr>')
document.write('  </table>')
document.write('</div>')